server {
    listen 80;
    index index.php index.html; #procura por esses arquivos ao receber uma request
    error_log  /var/log/nginx/error.log; #registra erros de servidor
    access_log /var/log/nginx/access.log; #registra logs de acesso
    root /var/www/backend/public; #local onde é buscado o arquivo index

    location ~ \.php$ {
        try_files $uri =404; #Se o arquivo .php solicitado explicitamente não existir no servidor, ele interrompe na hora e devolve um erro 404 Not Found
        fastcgi_split_path_info ^(.+\.php)(/.+)$; #Divide a URL em duas partes: o caminho real do script PHP e as informações adicionais de rota que vêm depois dele
        fastcgi_pass app:9000; #Pegue esse arquivo e envie para o container chamado app na porta 9000
        fastcgi_index index.php; #Define o arquivo padrão de processamento caso a requisição FastCGI chegue sem um nome de arquivo explícito.
        include fastcgi_params; #Inclui uma série de configurações padrão do Nginx que dizem ao PHP informações sobre a requisição (como o IP do usuário, o tipo de requisição (POST/GET), etc).
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; #Esta linha diz ao PHP exatamente onde encontrar o arquivo físico dentro do container para ser executado
        fastcgi_param PATH_INFO $fastcgi_path_info; #Informa ao PHP os caminhos virtuais da URL, permitindo que o roteador do Laravel entenda se você está acessando
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string; #verifica se é arquivo ou pasta, se não, pega a url e joga para o laravel
        gzip_static on;
    }
}